# Generated by Django 3.2.4 on 2021-07-04 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='re_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='postings.comment'),
        ),
    ]
